runtime: python
runtime_config:
  python_version: 3

env: flex 

entrypoint: gunicorn -b :$PORT main:app 

manual_scaling:
  instances: 1
resources:
  cpu: 4
  memory_gb: 4
  disk_size_gb: 10

env_variables:
  BUCKET_NAME: "test-proyect-319922.appspot.com"

handlers:
- url: /static
  static_dir: static

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
